### ISSUE TITLE
rvmi-rekall TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by monstahalien** [fireeye/rvmi#5]
Using rekall -f qmp-sock, I got this error
```
2017-10-21 12:30:59,115:CRITICAL:root:quote_from_bytes() expected bytes. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.6.0', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/rekal.py", line 102, in main
    user_session.plugins.load_as().GetPhysicalAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 372, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 471, in GuessAddressSpace
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/addrspaces/aff4.py", line 140, in __init__
    self._AutoLoadAFF4Volume(volume_path)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/addrspaces/aff4.py", line 202, in _AutoLoadAFF4Volume
    with self.resolver.AFF4FactoryOpen(path) as volume:
  File "/usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post3-py2.7.egg/pyaff4/data_store.py", line 353, in AFF4FactoryOpen
    cached_obj = self.ObjectCache.Get(urn)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post3-py2.7.egg/pyaff4/data_store.py", line 109, in Get
    key = rdfvalue.URN(urn).SerializeToString()
  File "/usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post3-py2.7.egg/pyaff4/rdfvalue.py", line 243, in SerializeToString
    components = self.Parse()
  File "/usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post3-py2.7.egg/pyaff4/rdfvalue.py", line 262, in Parse
    return self._Parse(self.value)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post3-py2.7.egg/pyaff4/rdfvalue.py", line 46, in Wrapped
    f.memo_pad[key] = f(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4-0.26.post3-py2.7.egg/pyaff4/rdfvalue.py", line 280, in _Parse
    path=urllib.request.pathname2url(value),
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 1594, in pathname2url
    return quote(pathname)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/parse.py", line 700, in quote
    return quote_from_bytes(string, safe)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/parse.py", line 725, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```
Ubuntu 16.04 uname -r
```4.10.17-041017-generic```

rvmi's rekall --version
```
This is Rekall Version 1.6.0 (Gotthard)
{u'rvmi_codename': u'Augustiner', 'pep440': u'1.6.0', u'rvmi_version': u'0.1', 'error': 'Not in a git repository.', u'version': u'1.6.0', u'rc': u'0', u'post': u'0', u'codename': u'Gotthard'}
```

I've added a print in parse.py line 725, and rekall called the `quote_from_bytes` function twice. The first print instance printed the qmp sock path while the second instance None. I've also tried adding `--repository_path rekall-profiles`, the error still shows.

These are the apt modules (which are prerequisite) that I've installed from fresh Ubuntu 16.04 setup.
```
sudo apt-get install libffi-dev lib32ncurses5-dev libssl-dev libgtk2.0-dev
sudo apt-get install python-pip python-setuptools python-dev build-essential 
pip install pyasn1
```

I've updated the kernel using the mainline build:
```
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.10.17/
```

I'm not sure if there was a mistake in my rvmi installation that is causing the error.

**Comment by likvidera** [comment]
Making sure pyaff4==0.24.post3 is installed and used by rekall solved it for me.

**Comment by monstahalien** [comment]
Thanks @likvidera and after adding that, the error have changed.
```2017-11-10 11:00:03,581:CRITICAL:root:'NoneType' object has no attribute 'has_key'. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.6.0', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/rekal.py", line 102, in main
    user_session.plugins.load_as().GetPhysicalAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 372, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 471, in GuessAddressSpace
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/addrspaces/qmp_as.py", line 48, in __init__
    vmi.connect()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/iface.py", line 158, in connect
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/iface.py", line 166, in close
    self.cont()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/iface.py", line 175, in cont
    rsp = self._qmp.command("cont")
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/qmp/qmp.py", line 192, in command
    if ret.has_key('error'):
AttributeError: 'NoneType' object has no attribute 'has_key'
```

**Comment by monstahalien** [comment]
Continuing with @likvidera's suggestion, I've finally got it to work with this specific pyasn1 version.
`pip install pyasn1==0.3.4`


```
[1] qmp-sock 14:42:43> pslist
---------------------> pslist()800000 (0xa00000) 
_EPROCESS          name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
---------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
0x83d34908 System                   4      0           74          402          - False  2017-11-10 20:38:09Z     -                       
0x843c5d40 smss.exe               232      4            2           29          - False  2017-11-10 20:38:09Z     -                       
0x8435d5f0 csrss.exe              312    304            8          223          0 False  2017-11-10 20:38:10Z     -                       
0x83d9a200 wininit.exe            360    304            4           79          0 False  2017-11-10 20:38:10Z     -                       
0x83d9a520 csrss.exe              372    352            7           74          1 False  2017-11-10 20:38:10Z     -                       
0x84334440 winlogon.exe           412    352            5           93          1 False  2017-11-10 20:38:10Z     -                       
0x84992408 services.exe           456    360            9          164          0 False  2017-11-10 20:38:10Z     -                       
0x8499ab90 lsass.exe              468    360            5          388          0 False  2017-11-10 20:38:10Z     -                       
0x8499cc80 lsm.exe                476    360            9          131          0 False  2017-11-10 20:38:10Z     -                       
0x849cb988 svchost.exe            580    456           10          331          0 False  2017-11-10 20:38:10Z     -                       
0x849dc130 svchost.exe            648    456            5          166          0 False  2017-11-10 20:38:10Z     -                       
0x849f3030 svchost.exe            700    456           14          304          0 False  2017-11-10 20:38:10Z     -                       
0x84a067d0 LogonUI.exe            756    412            6          173          1 False  2017-11-10 20:38:10Z     -                       
0x84a21030 svchost.exe            820    456           14          250          0 False  2017-11-10 20:38:11Z     -                       
0x84a36030 svchost.exe            860    456           26          631          0 False  2017-11-10 20:38:11Z     -                       
0x84a48270 svchost.exe            948    456           12          234          0 False  2017-11-10 20:38:11Z     -                       
0x84b61030 svchost.exe           1036    456           15          328          0 False  2017-11-10 20:38:11Z     -                       
0x84b9fc20 spoolsv.exe           1152    456            5           74          0 False  2017-11-10 20:38:11Z     -                       
0x84bd85b8 svchost.exe           1188    456           19          293          0 False  2017-11-10 20:38:11Z     -                       
0x84c09a60 svchost.exe           1292    456            8          153          0 False  2017-11-10 20:38:11Z     -                       
Out<14:42:57> Plugin: pslist (WinPsList)                 
```
