### ISSUE TITLE
QMP doesn't work

### ISSUE THREAD

**Issue by sharinko** [fireeye/rvmi#6]
OS: Ubuntu 16.04.3 LTS  (fresh install)

```

 rekall -f ./win7
2018-02-03 10:08:51,111:CRITICAL:root:The command vmi-get-vminfo has not been found. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.6.0', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/rekal.py", line 102, in main
    user_session.plugins.load_as().GetPhysicalAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 372, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 471, in GuessAddressSpace
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/addrspaces/vmem.py", line 106, in __init__
    0xbed2bed0, 0xbad1bad1, 0xbed2bed2, 0xbed3bed3],
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/obj.py", line 534, in method
    proxied = self.proxied()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/obj.py", line 618, in proxied
    return self.v()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/obj.py", line 634, in v
    data = self.obj_vm.read(self.obj_offset, self.obj_size)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/addrspaces/qmp_as.py", line 59, in read
    return self.session.vmi.read_mem(offset,size)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/iface.py", line 424, in read_mem
    for i, page in enumerate(self.get_pages(start_page,num_pages)):
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/iface.py", line 392, in get_pages
    if(offset >= self.guest_state.mem_size):
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/utils.py", line 1012, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/common.py", line 65, in mem_size
    vminfo = self.vmi.get_vminfo()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/iface.py", line 146, in get_vminfo
    rsp = self._qmp.command("vmi-get-vminfo")
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/vmi/qmp/qmp.py", line 193, in command
    raise Exception(ret['error']['desc'])
Exception: The command vmi-get-vminfo has not been found



```
```
nc -U ./win7
{"QMP": {"version": {"qemu": {"micro": 50, "minor": 8, "major": 2}, "package": " (-dirty)"}, "capabilities": []}}
{"execute" : "qmp_capabilities"} 
{"return": {}}
{ "execute" : "vmi-get-vminfo" }
{"error": {"class": "CommandNotFound", "desc": "The command vmi-get-vminfo has not been found"}}

```

**Comment by sharinko** [comment]
Solved this issue by upgrading the kernel to 4.10.17 and reinstalling rvmi.
